### ISSUE TITLE
(node) warning: possible EventEmitter memory leak detected. 11 __ALL__ listeners added. Use emitter.setMaxListeners() to increase limit. Trace

### ISSUE THREAD

**Issue by icarogregorio** [netsmarttech/node-red-contrib-s7#4]
Testing with 30 or more tags, this warning has been appeared to me:

```
(node) warning: possible EventEmitter memory leak detected. 11 __ALL__ listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at S7Endpoint.addListener (events.js:239:17)
    at S7Endpoint.Node.on (/usr/lib/node_modules/node-red/red/runtime/nodes/Node.js:80:14)
    at new S7In (/usr/lib/node_modules/node-red-contrib-s7/red/s7.js:281:35)
    at createNode (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:302:18)
    at Flow.start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:87:35)
    at start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:264:29)
    at /usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:121:25
    at tryCatchReject (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:27:9)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

Anyone have an idea about this ?

**Comment by gfcittolin** [comment]
Hi,

This was just a standard warning from EventEmitter from the S7 Endpoint node that we use underlying to "inform" the S7 In nodes about new data. I just removed this limitation, so by upgrading the node you won't see this warning anymore
