### ISSUE TITLE
Warning on start

### ISSUE THREAD

**Issue by icarogregorio** [netsmarttech/node-red-contrib-s7#7]
When I start the node-red I got the following message:

`(node) warning: possible EventEmitter memory leak detected. 11 __STATUS__ listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at S7Endpoint.addListener (events.js:239:17)
    at S7Endpoint.Node.on (/usr/lib/node_modules/node-red/red/runtime/nodes/Node.js:80:14)
    at new S7In (/usr/lib/node_modules/node-red-contrib-s7/red/s7.js:261:23)
    at createNode (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:276:18)
    at Flow.start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:87:35)
    at start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:284:29)
    at /usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:138:21
    at tryCatchReject (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:27:9)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
(node) warning: possible EventEmitter memory leak detected. 11 __ALL__ listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at S7Endpoint.addListener (events.js:239:17)
    at S7Endpoint.Node.on (/usr/lib/node_modules/node-red/red/runtime/nodes/Node.js:80:14)
    at new S7In (/usr/lib/node_modules/node-red-contrib-s7/red/s7.js:281:35)
    at createNode (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:276:18)
    at Flow.start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:87:35)
    at start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:284:29)
    at /usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:138:21
    at tryCatchReject (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:27:9)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
26 Jun 17:23:12 - [info] Started flows
26 Jun 17:23:12 - [error] [MySQLdatabase:47e21f82.2f7e2] Error: connect ETIMEDOUT
26 Jun 17:23:32 - [error] [mysql:Mysql] Database not connected
26 Jun 17:26:56 - [info] Stopping flows
26 Jun 17:26:58 - [info] Stopped flows
26 Jun 17:26:58 - [info] Starting flows
(node) warning: possible EventEmitter memory leak detected. 11 __STATUS__ listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at S7Endpoint.addListener (events.js:239:17)
    at S7Endpoint.Node.on (/usr/lib/node_modules/node-red/red/runtime/nodes/Node.js:80:14)
    at new S7In (/usr/lib/node_modules/node-red-contrib-s7/red/s7.js:261:23)
    at createNode (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:276:18)
    at Flow.start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:87:35)
    at start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:284:29)
    at /usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:138:21
    at tryCatchReject (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:27:9)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
(node) warning: possible EventEmitter memory leak detected. 11 __ALL__ listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at S7Endpoint.addListener (events.js:239:17)
    at S7Endpoint.Node.on (/usr/lib/node_modules/node-red/red/runtime/nodes/Node.js:80:14)
    at new S7In (/usr/lib/node_modules/node-red-contrib-s7/red/s7.js:281:35)
    at createNode (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:276:18)
    at Flow.start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:87:35)
    at start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:284:29)
    at /usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:138:21
    at tryCatchReject (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:27:9)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
`
Please what is this ?

**Comment by gfcittolin** [comment]
Hi,

This was already reported on #4. That was not really a bug, but just a warning from the EventEmitter we use to propagate the variable changes. This was already fixed on [1.1.2](https://github.com/netsmarttech/node-red-contrib-s7/commit/b6f8bd34c7ce0fee5bea2fca949d2fce51f45e2c), try updating to the latest version and you shouldn't see this anymore
